# Generated by Django 5.0.1 on 2025-11-16 04:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(help_text='Formato: +56912345678', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Formato: +56912345678')])),
                ('tipo_usuario', models.CharField(choices=[('PACIENTE', 'Paciente'), ('PROFESIONAL', 'Profesional'), ('ADMIN', 'Administrador')], default='PACIENTE', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_consulta_minutos', models.IntegerField(default=30, help_text='Duración por defecto de la consulta en minutos')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='paciente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rut', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}-[\\dkK]$', 'Formato: 12345678-9')])),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('inasistencias_consecutivas', models.IntegerField(default=0)),
                ('bloqueado', models.BooleanField(default=False)),
                ('fecha_ultimo_bloqueo', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profesional', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_registro', models.CharField(help_text='Número de registro profesional', max_length=50, unique=True)),
                ('duracion_consulta_custom', models.IntegerField(blank=True, help_text='Si se especifica, sobrescribe la duración de la especialidad', null=True)),
                ('atiende_lunes', models.BooleanField(default=True)),
                ('atiende_martes', models.BooleanField(default=True)),
                ('atiende_miercoles', models.BooleanField(default=True)),
                ('atiende_jueves', models.BooleanField(default=True)),
                ('atiende_viernes', models.BooleanField(default=True)),
                ('atiende_sabado', models.BooleanField(default=False)),
                ('atiende_domingo', models.BooleanField(default=False)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='usuarios.especialidad')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
    ]
